import React, { useState } from "react";
import { MdOutlineKeyboardArrowDown, MdKeyboardArrowUp } from "react-icons/md";
import { motion } from "framer-motion";
import "./faq.css";

const data = [
  {
    question: "What is an AI writing website, and how does it work?",
    answer:
      "An AI writing website employs advanced artificial intelligence algorithms to generate human-like text based on user inputs. Users can provide prompts, topics, or requirements, and the AI system generates customized content accordingly. The process involves natural language processing and machine learning to understand and mimic human writing styles",
  },
  {
    question:
      "Can I trust the AI-generated content for accuracy and reliability?",
    answer:
      "While AI writing has made significant strides, it's essential to understand that the generated content is based on patterns learned from diverse sources. Users should review and verify the accuracy of the content for their specific needs. The AI tool is a helpful assistant, but final responsibility for accuracy rests with the user.",
  },
  {
    question:
      "Is the AI capable of understanding specific writing styles or industry jargon?",
    answer:
      "Yes, AI writing models are trained on a vast amount of data, including diverse writing styles and industry-specific language. The system can adapt to different tones, styles, and jargon, making it suitable for various purposes, from creative writing to technical content within specific domains.",
  },
  {
    question:
      "How do I ensure the originality of the content generated by the AI?",
    answer:
      "AI writing websites often incorporate measures to promote originality. Users can take advantage of features such as plagiarism checks to ensure that the generated content is unique. Additionally, users should customize prompts and review the output to make the content more personalized and original.",
  },
  {
    question: "What types of content can I create using an AI writing website?",
    answer:
      "AI writing tools are versatile and can assist in creating a wide range of content, including blog posts, articles, marketing copy, creative writing, and more. The key is to provide clear instructions to the AI based on the specific type and tone of content desired. Users can experiment with different prompts to achieve the desired results for their writing projects.",
  },
];

const fadeInVariants = {
  hidden: {
    opacity: 0,
    x: 100,
  },
  visible: {
    opacity: 1,
    x: 0,
    transition: {
      delay: 0.1,
      duration: 1,
    },
  },
};

const FAQ = () => {
  const [selected, setSelected] = useState(null);
  const toggle = (i) => {
    if (selected === i) {
      return setSelected(null);
    }

    setSelected(i);
  };
  return (
    <div className="faq section__padding" id="faq">
      <motion.div
        variants={fadeInVariants}
        initial="hidden"
        whileInView="visible"
        className="faq__container"
      >
        <div className="faq__container-header">
          <h1 className="gradient__text">Frequently Asked Question</h1>
          <p>
            Have more questions? <span>Send us an email.</span>
          </p>
        </div>
        <div className="faq__accordion">
          {data.map((item, i) => (
            <div className="faq__item">
              <div className="faq__question" onClick={() => toggle(i)}>
                <h3>{item.question}</h3>
                <span>
                  {selected === i ? (
                    <MdKeyboardArrowUp size={30} />
                  ) : (
                    <MdOutlineKeyboardArrowDown size={30} />
                  )}
                </span>
              </div>
              <div
                className={selected === i ? "faq__answer show" : "faq__answer"}
              >
                {item.answer}
              </div>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default FAQ;
